### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by q3e** [shekhargulati/spring-boot-react-maven-starter#1]

**Comment by shekhargulati** [comment]
Hello @bnovf, I plan to maintain it if there are people using it. Are there any specific questions that I can answer?

**Comment by sukeshlaghate** [comment]
Hi shekhar,

I followed all the instructions mentioned in Readme file. However after running command 
$ java -jar backend/target/backend-0.1.0-SNAPSHOT.jar

I get following error when accessing localhost:8080

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Nov 30 13:07:18 IST 2017
There was an unexpected error (type=Not Found, status=404).
No message available

request you to help in resolving this issue.

**Comment by shekhargulati** [comment]
@sukeshlaghate I have fixed the issue. Please pull the changes from Github repository again. The problem was frontend was getting build after the backend jar is created. This means frontend assets were not in the Spring Boot executable jar. Please try again. Let me know if you face any issue.
